version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  project: ZKWeb.MVVMDemo.sln
  verbosity: minimal
after_build:
- cmd: >-
    cd src\ZKWeb.MVVMDemo.Console

    dotnet run -f netcoreapp1.1